name: Frontend Test Pipeline

on:
  push:
    paths:
      - "front/**"
    branches:
      - main
  pull_request:
    paths:
      - "front/**"
    types: [opened, synchronize, edited]
    branches:
      - main
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [12.x]

    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: E2E on Chrome
        uses: cypress-io/github-action@v2
        with:
          working-directory: front
          start: yarn start
          browser: chrome
          headless: true
          record: false
